{
 "title": "Python - Supervision",
 "description": "Formating all computer-related data to Grafana",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Memory usage of 8.59 GB",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  percent_used\nFROM memory_usage\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Disk Usage of 233.5GB",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$B / $A * 100", "type": "math" }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,$__interval),\n  avg(cpu_percent) AS \"CPU %\"\nFROM cpu_usage\nWHERE\n  $__timeFilter(timestamp)\nGROUP BY 1\nORDER BY $__timeGroup(timestamp,$__interval)"
    }
   ]
  },
  {
   "title": "Net IO",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,$__interval),\n  variance(bytes_received) AS \"received\"\nFROM net_io_counter\nWHERE\n  $__timeFilter(timestamp) AND\n  nic = 'en0'\nGROUP BY 1\nORDER BY $__timeGroup(timestamp,$__interval)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,$__interval),\n  variance(bytes_sent) AS \"sent\"\nFROM net_io_counter\nWHERE\n  $__timeFilter(timestamp) AND\n  nic = 'en0'\nGROUP BY 1\nORDER BY $__timeGroup(timestamp,$__interval)"
    }
   ]
  }
 ]
}